acl "clients" {
    127.0.0.0/8;
    10.0.0.0/8;
};

options {
    directory "/var/cache/bind";
    listen-on { any; };
    listen-on-v6 { none; };
    recursion yes;
    allow-query { clients; };
    allow-recursion { clients; };
    allow-query-cache { clients; };
    allow-transfer { none; };
    forward only;
    forwarders { 1.1.1.1; 1.0.0.1; };
    dnssec-validation auto;
};

zone "lylat.space" {
    type primary;
    file "/etc/bind/lylat.space.zone";
    allow-update { none; };
};
