variable "name" {
  description = "VM hostname, derived by the caller."
  type        = string
}

variable "vm" {
  description = "Placement, management addressing and ordered NICs for one VM."
  type = object({
    image              = optional(string)
    node               = string
    vm_id              = number
    cores              = optional(number)
    memory_mb          = optional(number)
    bridge             = optional(string)
    started            = optional(bool)
    tags               = optional(list(string))
    management_address = optional(string, "dhcp")
    gateway            = optional(string)
    config = optional(object({
      datastore_id            = optional(string)
      import_image            = optional(string)
      description             = optional(string)
      tags                    = optional(list(string))
      started                 = optional(bool)
      keyboard_layout         = optional(string)
      migrate                 = optional(bool)
      on_boot                 = optional(bool)
      reboot                  = optional(bool)
      stop_on_destroy         = optional(bool)
      agent_enabled           = optional(bool)
      boot_order              = optional(list(string))
      disk_interface          = optional(string)
      disk_iothread           = optional(bool)
      disk_size_gb            = optional(number)
      cloud_init              = optional(bool)
      cloud_init_interface    = optional(string)
      cloud_init_datastore_id = optional(string)
      user_data_file_id       = optional(string)
      management_bridge       = optional(string)
      network_model           = optional(string)
      network_disconnected    = optional(bool)
      management_mtu          = optional(number)
      underlay_mtu            = optional(number)
      serial_device           = optional(bool)
      cpu_cores               = optional(number)
      cpu_type                = optional(string)
      cpu_flags               = optional(list(string))
      cpu_hotplugged          = optional(number)
      cpu_limit               = optional(number)
      cpu_numa                = optional(bool)
      cpu_sockets             = optional(number)
      cpu_units               = optional(number)
      memory_mb               = optional(number)
      memory_floating_mb      = optional(number)
      memory_keep_hugepages   = optional(bool)
      memory_shared_mb        = optional(number)
      operating_system_type   = optional(string)
      vga_memory              = optional(number)
      vga_type                = optional(string)
      timeout_clone           = optional(number)
      timeout_create          = optional(number)
      timeout_migrate         = optional(number)
      timeout_reboot          = optional(number)
      timeout_shutdown_vm     = optional(number)
      timeout_start_vm        = optional(number)
      timeout_stop_vm         = optional(number)
    }), {})
    network_devices = optional(list(object({
      bridge       = string
      vlan_id      = optional(number)
      mac_address  = optional(string)
      model        = optional(string)
      mtu          = optional(number)
      disconnected = optional(bool)
    })), [])
  })
}
