pve_leaf = {
  proxmox = {
    endpoint     = "https://10.20.7.17:8006"
    insecure     = false
    ssh_username = "root"
    ssh_agent    = true
  }

  vm_config = {
    hostname_prefix          = "vtep-"
    vm_id_offset             = 700
    management_prefix        = "10.20.10.0/24"
    management_cidr          = 16
    underlay_local_as_base   = 700
    default_underlay_bridges = ["vmbr4001", "vmbr4002", "vmbr4000"]
    datastore_id             = "ceph_rbd"
    import_image             = "cephfs:import/vyos-1.5-rolling-202608270227-generic-amd64.qcow2"
    description              = "managed by opentofu"
    tags                     = ["opentofu", "debian", "vyos", "vxlan"]
    started                  = true
    keyboard_layout          = "en-us"
    migrate                  = false
    on_boot                  = true
    reboot                   = false
    stop_on_destroy          = true
    agent_enabled            = true
    boot_order               = ["virtio0"]
    disk_interface           = "virtio0"
    disk_iothread            = true
    disk_size_gb             = 10
    cloud_init               = true
    cloud_init_interface     = "scsi0"
    cloud_init_datastore_id  = "ceph_rbd"
    user_data_file_id        = "cephfs:snippets/vyos_api.yml"
    management_bridge        = "vmbr0"
    network_model            = "virtio"
    network_disconnected     = false
    management_mtu           = 0
    underlay_mtu             = 1
    serial_device            = true
    cpu_cores                = 4
    cpu_type                 = "x86-64-v2-AES"
    cpu_flags                = []
    cpu_hotplugged           = 0
    cpu_limit                = 0
    cpu_numa                 = false
    cpu_sockets              = 1
    cpu_units                = 1024
    memory_mb                = 4096
    memory_floating_mb       = 0
    memory_keep_hugepages    = false
    memory_shared_mb         = 0
    operating_system_type    = "l26"
    vga_memory               = 16
    vga_type                 = "std"
    timeout_clone            = 1800
    timeout_create           = 1800
    timeout_migrate          = 1800
    timeout_reboot           = 1800
    timeout_shutdown_vm      = 1800
    timeout_start_vm         = 1800
    timeout_stop_vm          = 300
  }
}
